server:
  port : 8080
  servlet:
    context-path: /api/bookstore
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/taman"
    username: root
    password: root
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: none
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: minhnghia11202@gmail.com
    password: wjxd sdvx uook zwto
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true


  web:
    resources:
      static-locations=classpath:/static/:
jwt:
  #  expiration: 2592000
  #    #30 days = 30 * 24 * 60 * 60
  #  secretKey: Minh Nghia
  signerKey: "z+7kjfwfgxuzW2+1/EVCduqLWkVwR/atuCqg+EtTogGK5RdioGkeSeY3Mfyps89G"
  valid-duration: 3600
  refreshable-duration: 3600

