server:
  port : 8080
  servlet:
    context-path: /api/bookstore
spring:
  jackson:
    time-zone: Asia/Ho_Chi_Minh
  datasource:
    url: "jdbc:mysql://localhost:3306/taman"
    username: root
    password: root
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: none
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: minhnghia11202@gmail.com
    password: wjxd sdvx uook zwto
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  web:
    resources:
      static-locations=classpath:/static/:

jwt:
  signerKey: "z+7kjfwfgxuzW2+1/EVCduqLWkVwR/atuCqg+EtTogGK5RdioGkeSeY3Mfyps89G"
  valid-duration: 36000
  refreshable-duration: 36000

vnp:
  pay-url: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
  return-url: "${VNPAY_RETURN_URI:http://localhost:4200/payment-callback}"
  tmn-code: "C5RVDNZY"
  secret-key: "4Y3RLXMHX39ARV9LX887Y7K4V5C4VD49"
  api-url: "https://sandbox.vnpayment.vn/merchant_webapi/api/transaction"
